"""Named trading universes.

A caveat that matters more than the code: these lists are *today's* constituents, so
any backtest over them inherits survivorship bias — companies that were liquidated or
delisted never appear. The bias inflates long-only returns most, and inflates a
dollar-neutral cross-sectional book much less, but it is never zero. For research that
has to stand up, replace ``US_LARGE_CAP`` with a point-in-time constituent history from
a vendor and load it through :func:`ml_trading.data.load_prices`.
"""

from __future__ import annotations

SECTOR_ETFS: tuple[str, ...] = (
    "XLB",
    "XLE",
    "XLF",
    "XLI",
    "XLK",
    "XLP",
    "XLU",
    "XLV",
    "XLY",
)

MACRO_ETFS: tuple[str, ...] = (
    "SPY",
    "QQQ",
    "IWM",
    "EFA",
    "EEM",
    "TLT",
    "IEF",
    "LQD",
    "HYG",
    "GLD",
    "DBC",
    "VNQ",
)

US_LARGE_CAP: tuple[str, ...] = (
    "AAPL",
    "ABT",
    "ACN",
    "ADBE",
    "ADI",
    "ADP",
    "AEP",
    "AIG",
    "AMAT",
    "AMD",
    "AMGN",
    "AMT",
    "AMZN",
    "AON",
    "APD",
    "AXP",
    "BA",
    "BAC",
    "BDX",
    "BK",
    "BKNG",
    "BMY",
    "BSX",
    "C",
    "CAT",
    "CB",
    "CI",
    "CL",
    "CMCSA",
    "CME",
    "COF",
    "COP",
    "COST",
    "CRM",
    "CSCO",
    "CSX",
    "CVS",
    "CVX",
    "D",
    "DE",
    "DHR",
    "DIS",
    "DUK",
    "EA",
    "ECL",
    "EMR",
    "EOG",
    "EQIX",
    "ETN",
    "EXC",
    "F",
    "FDX",
    "GD",
    "GE",
    "GILD",
    "GIS",
    "GM",
    "GOOGL",
    "GS",
    "HAL",
    "HD",
    "HON",
    "HUM",
    "IBM",
    "ICE",
    "INTC",
    "INTU",
    "ISRG",
    "ITW",
    "JNJ",
    "JPM",
    "K",
    "KMB",
    "KO",
    "LIN",
    "LLY",
    "LMT",
    "LOW",
    "MA",
    "MCD",
    "MDT",
    "MET",
    "MMC",
    "MMM",
    "MO",
    "MRK",
    "MS",
    "MSFT",
    "MSI",
    "MU",
    "NEE",
    "NKE",
    "NOC",
    "NSC",
    "NVDA",
    "ORCL",
    "OXY",
    "PEP",
    "PFE",
    "PG",
    "PGR",
    "PLD",
    "PNC",
    "PSA",
    "PSX",
    "QCOM",
    "REGN",
    "ROP",
    "ROST",
    "RTX",
    "SBUX",
    "SCHW",
    "SHW",
    "SLB",
    "SO",
    "SPG",
    "SPGI",
    "SYK",
    "T",
    "TGT",
    "TJX",
    "TMO",
    "TRV",
    "TSLA",
    "TXN",
    "UNH",
    "UNP",
    "UPS",
    "USB",
    "V",
    "VLO",
    "VZ",
    "WFC",
    "WM",
    "WMT",
    "XOM",
    "ZTS",
)

UNIVERSES: dict[str, tuple[str, ...]] = {
    "sector_etfs": SECTOR_ETFS,
    "macro_etfs": MACRO_ETFS,
    "etfs": tuple(dict.fromkeys(SECTOR_ETFS + MACRO_ETFS)),
    "us_large_cap": US_LARGE_CAP,
    "us_large_cap_plus_etfs": tuple(dict.fromkeys(US_LARGE_CAP + SECTOR_ETFS + MACRO_ETFS)),
}


def resolve(symbols: tuple[str, ...] | list[str]) -> tuple[str, ...]:
    """Expand any ``@universe_name`` entries in a symbol list."""
    out: list[str] = []
    for symbol in symbols:
        if symbol.startswith("@"):
            name = symbol[1:]
            if name not in UNIVERSES:
                raise ValueError(f"unknown universe: {name}. Known: {sorted(UNIVERSES)}")
            out.extend(UNIVERSES[name])
        else:
            out.append(symbol)
    return tuple(dict.fromkeys(out))
